=== luis1ribeiro/MEI-MajorsDegree/PLC/PRI/TPCs/tpc2/p-record.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT project-record (meta, workteam, abstract, deliverables?, date?)>
<!ELEMENT meta (title,subtitle?, key-name, supervisor, b_date, e_date)>

<!ELEMENT title (#PCDATA)>
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT key-name (#PCDATA)>
<!ELEMENT b_date (#PCDATA)>
<!ELEMENT e_date (#PCDATA)>

<!ELEMENT supervisor (#PCDATA)>
<!ATTLIST supervisor
            href CDATA #REQUIRED>

<!ELEMENT abstract (p+)>
<!ELEMENT p (#PCDATA|b|i|u|url)* >
<!ELEMENT b (#PCDATA|i|u|url)*>
<!ELEMENT i (#PCDATA|b|u|url)*>
<!ELEMENT u (#PCDATA|b|i|url)*>
<!ELEMENT url (#PCDATA)>
<!ATTLIST url
            href CDATA #REQUIRED>
 
<!ELEMENT workteam (teammate+)>
<!ELEMENT teammate (id, name, email)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ATTLIST email
            href CDATA #REQUIRED>

<!ELEMENT deliverables (url+)>

<!ELEMENT date (#PCDATA)>

=== luis1ribeiro/MEI-MajorsDegree/PLC/PRI/TPCs/tpc6/p-record.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project-record SYSTEM "p-record.dtd">
<project-record>
    <meta>
        <title>PRI_TPC6</title>
        <key-name>PRI_2020_TPC6</key-name>
        <supervisor href="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
        <b_date>/16/2020</b_date>
        <e_date>22/11/2020</e_date>
    </meta>
    <workteam>
        <teammate>
            <id>1</id>
            <name>Luís Ribeiro</name>
            <email href="mailto:a85954@alunos.uminho.pt">a85954@alunos.uminho.pt</email>
        </teammate>
    </workteam>
    <abstract>
        <p>Este é o <b>TPC6</b> da cadeira de <u>Processamento e Representação de Informação</u>.</p>
        <p> Foi criado um servidor em <b>Node JS</b> que mandava <i>requests</i> a um servidor <i>JSON</i> aberto noutra porta.</p>
        <p> Com a ajuda de <b>Formulários</b> foi possível inserir informação para o ficheiro <i>JSON</i>, através do método <i>POST</i>.
            Para mudar o estado de uma tarefa, usei o <i>AJAX</i> que manda um request à base dados para mudar de estado, quando carrego num botão.
        </p>
        <p>Github: <url href="https://github.com/luis1ribeiro/PRI2020">Luís Ribeiro - PRI2020</url></p>
    </abstract>
    <deliverables>
        <url href="db.json">JSON Server.</url>
        <url href="tp6.js">Servidor NODE JS.</url>
        <url href="static.js">Servidor NODE JS.</url>
        <url href="public">Pasta com ficheiros estáticos.</url>
    </deliverables>
</project-record>

=== luis1ribeiro/MEI-MajorsDegree/PLC/PRI/TPCs/tpc4/p-record.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project-record SYSTEM "p-record.dtd">
<project-record>
    <meta>
        <title>PRI_TPC4</title>
        <key-name>PRI_2020_TPC4</key-name>
        <supervisor href="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
        <b_date>05/11/2020</b_date>
        <e_date>06/11/2020</e_date>
    </meta>
    <workteam>
        <teammate>
            <id>1</id>
            <name>Luís Ribeiro</name>
            <email href="mailto:a85954@alunos.uminho.pt">a85954@alunos.uminho.pt</email>
        </teammate>
    </workteam>
    <abstract>
        <p>Este é o <b>TP4</b> da cadeira de <u>Processamento e Representação de Informação</u>.</p>
        <p>Inicialmente, criei uma <i>stylesheet</i> transformadora em <b>XSLT</b>, 
            em que todos os arqs estavam ordenados numericamente. 
        </p>
        <p>
            Depois, com a ajuda do <b>Node JS</b> foi criado um servidor que abria uma porta e respondia a <i>requests</i>
            no <i>path</i> do <b><i>URL</i></b>. 
        </p>
        <p>Github: <url href="https://github.com/luis1ribeiro/PRI2020">Luís Ribeiro - PRI2020</url></p>
    </abstract>
    <deliverables>
        <url href="arqtp4.xsl">XSL Document.</url>
        <url href="arq.xml">XML ARQ.</url>
        <url href="servtp4.js">Servidor NODE JS.</url>
    </deliverables>
</project-record>

=== luis1ribeiro/MEI-MajorsDegree/PLC/PRI/TPCs/tpc2/p-record.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project-record SYSTEM "p-record.dtd">
<project-record>
    <meta>
        <title>PRI_TPC2</title>
        <key-name>PRI_2020_TPC2</key-name>
        <supervisor href="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
        <b_date>20/10/2020</b_date>
        <e_date>24/10/2020</e_date>
    </meta>
    <workteam>
        <teammate>
            <id>1</id>
            <name>Luís Ribeiro</name>
            <email href="mailto:a85954@alunos.uminho.pt">a85954@alunos.uminho.pt</email>
        </teammate>
    </workteam>
    <abstract>
        <p>Este é o <b>TPC2</b> da cadeira de <u>Processamento e Representação de Informação</u>.</p>
        <p>Inicialmente, formalizei o problema e através do uso das ferramentas do <i>Oxygen XML Editor</i>, juntamente com o ficheiro <i>Document Type Definition</i>, gerei o <b><i>XML</i></b> necessário.</p>
        <p>Github: <url href="https://github.com/luis1ribeiro/PRI2020">Luís Ribeiro - PRI2020</url></p>
    </abstract>
    <deliverables>
        <url href="p-record.dtd">Document type Definition (DTD) do Project Record.</url>
    </deliverables>
</project-record>

=== luis1ribeiro/MEI-MajorsDegree/PLC/PRI/TPCs/tpc5/p-record.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project-record SYSTEM "p-record.dtd">
<project-record>
    <meta>
        <title>PRI_TPC5</title>
        <key-name>PRI_2020_TPC5</key-name>
        <supervisor href="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
        <b_date>09/11/2020</b_date>
        <e_date>16/11/2020</e_date>
    </meta>
    <workteam>
        <teammate>
            <id>1</id>
            <name>Luís Ribeiro</name>
            <email href="mailto:a85954@alunos.uminho.pt">a85954@alunos.uminho.pt</email>
        </teammate>
    </workteam>
    <abstract>
        <p>Este é o <b>TPC5</b> da cadeira de <u>Processamento e Representação de Informação</u>.</p>
        <p> Foi criado um servidor em <b>Node JS</b> que mandava <i>requests</i> a um servidor <i>JSON</i> aberto noutra porta </p>
        <p> Assim, em vez do servidor em Node servir páginas estáticas, serve páginas dinâmicas.</p>
        <p>Github: <url href="https://github.com/luis1ribeiro/PRI2020">Luís Ribeiro - PRI2020</url></p>
    </abstract>
    <deliverables>
        <url href="db.json">JSON Server.</url>
        <url href="escola.js">Servidor NODE JS.</url>
    </deliverables>
</project-record>

=== luis1ribeiro/MEI-MajorsDegree/PLC/PRI/TPCs/tpc3/p-record.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project-record SYSTEM "p-record.dtd">
<project-record>
    <meta>
        <title>PRI_TPC3</title>
        <key-name>PRI_2020_TPC3</key-name>
        <supervisor href="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
        <b_date>28/10/2020</b_date>
        <e_date>31/10/2020</e_date>
    </meta>
    <workteam>
        <teammate>
            <id>1</id>
            <name>Luís Ribeiro</name>
            <email href="mailto:a85954@alunos.uminho.pt">a85954@alunos.uminho.pt</email>
        </teammate>
    </workteam>
    <abstract>
        <p>Este é o <b>TPC3</b> da cadeira de <u>Processamento e Representação de Informação</u>.</p>
        <p>O objetivo deste TPC era criar uma <i>stylesheet</i> transformadora em <b>XSLT</b>, para através de um ficheiro XML de input, gerar um output com extensão HTML.</p>
        <p>Github: <url href="https://github.com/luis1ribeiro/PRI2020">Luís Ribeiro - PRI2020</url></p>
    </abstract>
    <deliverables>
        <url href="arq.dtd">Document type Definition (DTD) do ARQ.</url>
        <url href="arq.xml">XML ARQ.</url>
        <url href="arq.xsl">XSL Tabela ARQ.</url>
        <url href="arq2.xsl">XSL ARQ.</url>
    </deliverables>
</project-record>
